-- 코드를 입력하세요
SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = '30일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID 
       AND NOT (
           H.END_DATE < DATE('2022-11-01') OR 
           H.START_DATE > DATE('2022-11-30')
       )
WHERE 
    (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV') -- 자동차 종류 필터
    AND H.HISTORY_ID IS NULL -- 대여 가능 차량 필터
    AND C.DAILY_FEE * 30 * (1 - DP.DISCOUNT_RATE / 100) BETWEEN 500000 AND 2000000
ORDER BY 
    FEE DESC, 
    C.CAR_TYPE ASC, 
    C.CAR_ID DESC;
