-- 코드를 입력하세요
SELECT F.PRODUCT_ID,F.PRODUCT_NAME,SUM(F.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT F
JOIN FOOD_ORDER FO ON F.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE >= '2022-05-01' AND FO.PRODUCE_DATE <= '2022-05-31'
GROUP BY F.PRODUCT_ID, F.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID ASC;
