SELECT 
    f.FLAVOR
FROM 
    FIRST_HALF f
LEFT JOIN 
    JULY j ON f.FLAVOR = j.FLAVOR
GROUP BY 
    f.FLAVOR, f.TOTAL_ORDER
ORDER BY 
    SUM(IFNULL(j.TOTAL_ORDER, 0)) + f.TOTAL_ORDER DESC
LIMIT 3;
